const Data = {
  users: [
    {
      _id: 1,
      username: 'Mikul Hirani',
      image: './images/p4.jpg',
      uploaded: '18h',
      friendsList: [2, 3, 4, 5],
      photos: { tagged: [], personal: [] },
      videos: { tagged: [], personal: [] },
      tagLine: 'updated his cover photo',
      commonFriend: 'Harshad Vekaria',
      totalLikes: 100,
      totalComments: 12,
    },
    {
      _id: 2,
      username: 'Harshad Vekaria',
      image: './images/p2.jpg',
      uploaded: '2d',
      tagLine: 'Feeling HAPPY...',
      commonFriend: 'Bhavik Vekaria',
      totalLikes: 943,
      totalComments: 52,
    },
    {
      _id: 3,
      username: 'Nirav Rabadia',
      image: './images/p3.jpg',
      uploaded: '8h',
      tagLine: 'Somewhere in Africa',
      commonFriend: 'Mikul Hirani',
      totalLikes: 1562,
      totalComments: 121,
    },
    {
      _id: 4,
      username: 'Bhavik Hirani',
      image: './images/p4.jpg',
      uploaded: '11h',
      tagLine: 'Keep everyone happy',
      commonFriend: 'Divyesh Dabasia',
      totalLikes: 110,
      totalComments: 92,
    },
    {
      _id: 5,
      username: 'Divyesh Dabasia',
      image: './images/p5.jpg',
      uploaded: '3d',
      tagLine: 'Live like a KING!!',
      commonFriend: 'Nirav Rabadia',
      totalLikes: 1030,
      totalComments: 122,
    },
  ],
};
export default Data;
