const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: './images/p1.jpg',
      image2: '../images/p1.jpg',
      price: 120,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High Quality Product',
      countInStock: 10,
    },
    {
      _id: '2',
      name: 'Adidas Fit Shirt',
      category: 'Shirts',
      image: './images/p2.jpg',
      image2: '../images/p2.jpg',
      price: 170,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 55,
      description: 'High Quality Product And Long Lasting',
      countInStock: 0,
    },
    {
      _id: '3',
      name: 'Lacoste Free Shirt',
      category: 'Shirts',
      image: './images/p3.jpg',
      image2: '../images/p3.jpg',
      price: 80,
      brand: 'Lacoste',
      rating: 3.6,
      numReviews: 32,
      description: 'High Quality Product',
      countInStock: 13,
    },
    {
      _id: '4',
      name: 'Nike Slim Pant',
      category: 'Pants',
      image: './images/p4.jpg',
      image2: '../images/p1.jpg',
      price: 57,
      brand: 'Nike',
      rating: 4.9,
      numReviews: 34,
      description: 'High Quality Product',
      countInStock: 5,
    },
    {
      _id: '5',
      name: 'Puma Slim Shirt',
      category: 'Shirts',
      image: './images/p5.jpg',
      image2: '../images/p5.jpg',
      price: 43,
      brand: 'Puma',
      rating: 2.6,
      numReviews: 22,
      description: 'High Quality Product',
      countInStock: 8,
    },
    {
      _id: '6',
      name: 'Adidas Slim Pant',
      category: 'Pants',
      image: './images/p6.jpg',
      image2: '../images/p6.jpg',
      price: 143,
      brand: 'Adidas',
      rating: 4.7,
      numReviews: 104,
      description: 'High Quality Product And Long Lasting',
      countInStock: 0,
    },
  ],
};

export default data;
